os: Visual Studio 2017

environment:
  matrix:
    - platform: x64
      target: x86_64-pc-windows-msvc
      qtdir: C:\Qt\5.13.2\msvc2017_64
      sysdirname: SysWOW64

    - platform: x86
      target: i686-pc-windows-msvc
      qtdir: C:\Qt\5.13.2\msvc2017
      sysdirname: system32

cache:
  CGAL-4.13-Setup.exe -> appveyor.yml

install:
  - if "%PLATFORM%" == "x64"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%PLATFORM%" == "x86"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - if not exist CGAL-4.13-Setup.exe
      appveyor DownloadFile https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.13/CGAL-4.13-Setup.exe -FileName CGAL-4.13-Setup.exe
  - if "%PLATFORM%" == "x64"
    cd thirdparty/cgal/CGAL-4.13
  - if "%PLATFORM%" == "x86"
    CGAL-4.13-Setup.exe /S /D=%APPVEYOR_BUILD_FOLDER%\CGAL-4.13
  - if "%PLATFORM%" == "x86"
    cd CGAL-4.13
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% ../ -DBOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" ../ -DBOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0
  - msbuild /p:Configuration=Release ALL_BUILD.vcxproj
  - cd %APPVEYOR_BUILD_FOLDER%

  - cd thirdparty/instant-meshes
  - mkdir build
  - cd build
  - if "%PLATFORM%" == "x64"
    cmake -G "Visual Studio 15 2017" -A %PLATFORM% ../
  - if "%PLATFORM%" == "x86"
    cmake -G "Visual Studio 15 2017" ../
  - msbuild /p:Configuration=RelWithDebInfo ALL_BUILD.vcxproj
  - cd %APPVEYOR_BUILD_FOLDER%

build: false

test_script:
  - set PATH=%PATH%;%QTDIR%\bin
  
  - if "%PLATFORM%" == "x64"
    qmake "BOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0" "CGAL_DIR=%APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-4.13"
  - if "%PLATFORM%" == "x86"
    qmake "BOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0" "CGAL_DIR=%APPVEYOR_BUILD_FOLDER%\CGAL-4.13"
  - nmake -f Makefile.Release
  
  - cd lib
  - if "%PLATFORM%" == "x64"
    qmake "BOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0" "CGAL_DIR=%APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-4.13"
  - if "%PLATFORM%" == "x86"
    qmake "BOOST_INCLUDEDIR=C:\Libraries\boost_1_66_0" "CGAL_DIR=%APPVEYOR_BUILD_FOLDER%\CGAL-4.13"
  - nmake -f Makefile.Release
  
  - cd %APPVEYOR_BUILD_FOLDER%

after_test:
  # Check deps by Dependency Walker
  # Check Qt plugins by following https://wiki.qt.io/Deploy_an_Application_on_Windows
  - set /p VCRedistVersion=<"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt"
  - set VCREDIST_CRT_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Redist\MSVC\%VCRedistVersion%\%PLATFORM%\Microsoft.VC141.CRT

  - set TAG=%APPVEYOR_REPO_TAG_NAME%
  - if "%TAG%" == ""
    set TAG=unstable
  - if "%PLATFORM%" == "x64"
    set RELEASE_FILENAME=dust3d-%TAG%.zip
  - if "%PLATFORM%" == "x86"
    set RELEASE_FILENAME=dust3d-%TAG%-x86.zip
  - if "%TAG%" == "unstable"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\release\dust3d.pdb
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\release\dust3d.exe
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\lib\release\libdust3d.dll
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\lib\release\libdust3d.lib
  - if "%TAG%" == "unstable"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\instant-meshes\build\RelWithDebInfo\instant-meshes.pdb
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\instant-meshes\build\RelWithDebInfo\instant-meshes.dll
  - if "%TAG%" == "unstable"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\instant-meshes\build\ext_build\tbb\RelWithDebInfo\tbb.pdb
  - 7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\instant-meshes\build\ext_build\tbb\RelWithDebInfo\tbb.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-4.13\build\bin\Release\CGAL-vc140-mt-4.13.dll
  - if "%PLATFORM%" == "x86"
    7z a dust3d-%TAG%-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\CGAL-4.13\build\bin\Release\CGAL-vc140-mt-4.13.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-4.13\auxiliary\gmp\lib\libgmp-10.dll
  - if "%PLATFORM%" == "x86"
    7z a dust3d-%TAG%-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\CGAL-4.13\auxiliary\gmp\lib\libgmp-10.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% %APPVEYOR_BUILD_FOLDER%\thirdparty\cgal\CGAL-4.13\auxiliary\gmp\lib\libmpfr-4.dll
  - if "%PLATFORM%" == "x86"
    7z a dust3d-%TAG%-%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\CGAL-4.13\auxiliary\gmp\lib\libmpfr-4.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win64\bin\libcrypto-1_1-x64.dll
  - if "%PLATFORM%" == "x86"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win32\bin\libcrypto-1_1.dll
  - if "%PLATFORM%" == "x64"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win64\bin\libssl-1_1-x64.dll
  - if "%PLATFORM%" == "x86"
    7z a %RELEASE_FILENAME% C:\OpenSSL-v111-Win32\bin\libssl-1_1.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Widgets.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Gui.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Core.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\Qt5Network.dll
  - 7z a %RELEASE_FILENAME% %QTDIR%\bin\opengl32sw.dll
  - 7z a %RELEASE_FILENAME% "%VCREDIST_CRT_DIR%\msvcp140.dll"
  - 7z a %RELEASE_FILENAME% "%VCREDIST_CRT_DIR%\vcruntime140.dll"
  - mkdir platforms
  - copy %QTDIR%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\platforms\qwindows.dll
  - 7z a %RELEASE_FILENAME% -r %APPVEYOR_BUILD_FOLDER%\platforms\
  - mkdir imageformats
  - copy %QTDIR%\plugins\imageformats\qjpeg.dll %APPVEYOR_BUILD_FOLDER%\imageformats\qjpeg.dll
  - 7z a %RELEASE_FILENAME% -r %APPVEYOR_BUILD_FOLDER%\imageformats\
  - mkdir test
  - 7z e %RELEASE_FILENAME% -o%APPVEYOR_BUILD_FOLDER%\test *.* -r
  - cd /d %APPVEYOR_BUILD_FOLDER%\test
  - dust3d.exe :/resources/model-addax.ds3 -o addax.obj
  - dust3d.exe :/resources/model-addax.ds3 -o addax.fbx
  - dust3d.exe :/resources/model-addax.ds3 -o addax.glb
  - dust3d.exe :/resources/model-bicycle.ds3 -o bicycle.obj
  - dust3d.exe :/resources/model-bicycle.ds3 -o bicycle.fbx
  - dust3d.exe :/resources/model-bicycle.ds3 -o bicycle.glb
  - dust3d.exe :/resources/model-bob.ds3 -o bob.obj
  - dust3d.exe :/resources/model-bob.ds3 -o bob.fbx
  - dust3d.exe :/resources/model-bob.ds3 -o bob.glb
  - dust3d.exe :/resources/model-dog.ds3 -o dog.obj
  - dust3d.exe :/resources/model-dog.ds3 -o dog.fbx
  - dust3d.exe :/resources/model-dog.ds3 -o dog.glb
  - dust3d.exe :/resources/model-cat.ds3 -o cat.obj
  - dust3d.exe :/resources/model-cat.ds3 -o cat.fbx
  - dust3d.exe :/resources/model-cat.ds3 -o cat.glb
  - dust3d.exe :/resources/model-meerkat.ds3 -o meerkat.obj
  - dust3d.exe :/resources/model-meerkat.ds3 -o meerkat.fbx
  - dust3d.exe :/resources/model-meerkat.ds3 -o meerkat.glb
  - dust3d.exe :/resources/model-mosquito.ds3 -o mosquito.obj
  - dust3d.exe :/resources/model-mosquito.ds3 -o mosquito.fbx
  - dust3d.exe :/resources/model-mosquito.ds3 -o mosquito.glb

artifacts:
  - path: '*.zip'
    name: platform_zips

deploy:
  - provider: GitHub
    release: $(TAG)
    force_update: true
    auth_token:
      secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
    artifact: platform_zips
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: $(TAG)
    force_update: true
    auth_token:
      secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
    artifact: platform_zips
    draft: false
    prerelease: false
    on:
      branch: ci

  - provider: GitHub
    release: $(TAG)
    force_update: true
    auth_token:
      secure: Rhzhefjk89WN2tDht8vVKYAojGfR23LhDPKPxhQwbT7k3qswSWjmoFoDTpIHNfc0
    artifact: platform_zips
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true
